### ISSUE TITLE
Port matching.coffee to matching.ex

### ISSUE THREAD

**Issue by ryanwinchester** [sevenshores/zxcvbn-ex#2]
You can do a separate PR for each item, but you need to test it:

- [ ] `omnimatch/1`
- [x] `dictionary_match/2`
- [x] `reverse_dictionary_match/2`
- [ ] `l33t_match/3`
- [ ] `spatial_match/2`
- [ ] `repeat_match/1`
- [ ] `sequence_match/1`
- [ ] `regex_match/2`
- [ ] `date_match/1`

https://github.com/sevenshores/zxcvbn-ex/blob/master/lib/zxcvbn/matching.ex

**Comment by KrisLamote** [comment]
Interested in starting off with this one, but looks daunting..
Looking at some reference implementation primarily to get some valid test cases to work with - suggestions are welcome :)

**Comment by ryanwinchester** [comment]
I don't know helpful it is, but here are the original tests in coffeescript:

https://github.com/dropbox/zxcvbn/tree/master/test

**Comment by KrisLamote** [comment]
starting `repeat_match/1`, I find the scala project has very readable test cases
(https://github.com/tekul/szxcvbn)
