### ISSUE TITLE
Port time_estimates.coffee to time_estimates.ex

### ISSUE THREAD

**Issue by ryanwinchester** [sevenshores/zxcvbn-ex#4]
You can do a separate PR for each item, but you need to write tests for it:

- [ ] `estimate_attack_times/1`
- [x] `guesses_to_score/1`
- [x] `display_time/1`

https://github.com/sevenshores/zxcvbn-ex/blob/master/lib/zxcvbn/time_estimates.ex

**Comment by KrisLamote** [comment]
If/When my PR for `display_time/1` get's accepted, I could probably as well tackle `estimate_attack_times/1`
