### ISSUE TITLE
Port feedback.coffee to feedback.ex

### ISSUE THREAD

**Issue by ryanwinchester** [sevenshores/zxcvbn-ex#5]
You can do a separate PR for each item, but you need to write tests for it:

- [ ] `get_feedback/2`
- [ ] `get_match_feedback/2`
- [x] `get_dictionary_match_feedback/2`

https://github.com/sevenshores/zxcvbn-ex/blob/master/lib/zxcvbn/feedback.ex

**Comment by denysmedynskyi** [comment]
Can I take this?

**Comment by ryanwinchester** [comment]
Yep!

**Comment by delta1** [comment]
Hey @ryanwinchester ! I'm interested in picking this up as part of Hacktoberfest. As far as I can tell - `get_feedback/2` depends on `get_match_feedback/2` and the [original repo](/dropbox/zxcvbn) has no tests for this module? 

Do you have any specific tests you'd like to see? I'll do my best to cover the code in the meanwhile.

**Comment by delta1** [comment]
I'm guessing this was abandoned in favor of [techgaun/zxcvbn-elixir](/techgaun/zxcvbn-elixir) ?

Please let me know. 

Thanks!

**Comment by ryanwinchester** [comment]
I've planned on finishing this one eventually.
However, I haven't looked at that other one yet.

If it does a good job, I might just abandon this one. What's your opinion?

**Comment by delta1** [comment]
In all honesty, it already seems feature complete and is on hex as [zxcvbn](https://hexdocs.pm/zxcvbn). Sorry!
